android.usesSdkInManifest.disallowed=false
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableR8.fullMode=true
android.enableAppCompileTimeRClass=false
android.builtInKotlin=false
android.newDsl=false
android.r8.optimizedResourceShrinking=false
android.defaults.buildfeatures.resvalues=true
android.enableJetifier=true