android.enableR8.fullMode=true
android.enableJetifier=true
android.useAndroidX=true
android.aapt2FromMavenOverride=/data/data/com.jahangir/files/usr/bin/aapt2

org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=256m
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=true

kotlin.incremental=true