-allowaccessmodification
-ignorewarnings
-dontnote
-dontwarn **
-optimizations !code/simplification/arithmetic
-optimizationpasses 5
-overloadaggressively

-keep class rikka.shizuku.ShizukuProvider { *; }
-keep class rikka.shizuku.ShizukuProvider$* { *; }
-keep class moe.shizuku.api.BinderContainer { *; }
-keep class moe.shizuku.api.BinderContainer$* { *; }